### ISSUE TITLE
Updating of App

### ISSUE THREAD

**Issue by SebKrantz** [Stellenbosch-Econometrics/SA-Nowcast#5]
@byrongibby If you find time this weekend please give the app another update from the main branch, as the nowcast evolution graph needed some fixes (using 'relative' instead of 'stacked' bar chart for the news) and I added a few details on time series transformations applied in the About section. I also presume you scheduled an automatic restart of the app on Friday morning following the nowcast model run? 

In general, I am thinking: a further level of automation would be to sort of trigger the app restart by the RunSANowcast action completion on this repo (rather than setting an independent timer), and alongside perhaps also replace the app directory on the server with the contents of the app/ directory - thus keeping the app up to date with GH and allowing easy modification. This might be hard to program though (using the GitHub API)...

**Comment by byrongibby** [comment]
Done.

> I also presume you scheduled an automatic restart of the app on Friday morning following the nowcast model run?

Correct.

> In general, I am thinking: a further level of automation would be to sort of trigger the app restart by the RunSANowcast...

I agree that this is the direction we should move in, but I don't have to time to dedicate to it at this time. It would require the CI to run a number of Docker tasks as the app is deployed as a docker container.

**Comment by SebKrantz** [comment]
As far as I can see, the app has not been updated with todays nowcast ...

**Comment by SebKrantz** [comment]
So the June 16 nowcast is there, as seen from running the app offline below. There is no change in the value (no new data since last week), but the new nowcast is not available at [nowcast.codera.co.za](http://nowcast.codera.co.za/), so I'd say this needs immediate fixing @byrongibby if people are to see this as a reliable tool. I also wonder what the reason might be. The repo was updated at around 4am on the night from Thursday to friday. If the nowcasting app was restarted after that the new nowcast should be visible...

<img width="1229" alt="Screenshot at Jun 17 11-03-31" src="https://github.com/Stellenbosch-Econometrics/SA-Nowcast/assets/48053842/97cbb67d-e16b-4c24-b547-cbcc35682afb">

**Comment by SebKrantz** [comment]
The app has succesfully updated!
